name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print secret for debugging
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        echo "Raw AZURE_CREDENTIALS:"
        echo "$AZURE_CREDENTIALS"

        echo ""
        echo "Spaced characters:"
        echo "$AZURE_CREDENTIALS" | sed 's/./& /g'

        echo ""
        echo "Pretty JSON (if applicable):"
        echo "$AZURE_CREDENTIALS" | jq .
