name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        
      run: |
        echo $AZURE_CREDENTIALS >> secrets.txt


    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
